### ISSUE TITLE
New 'toggle unread' less informative

### ISSUE THREAD

**Issue by disconn3ct** [g2ttrss/g2ttrss-mobile#35]
With the new unread toggle, it is impossible to see if an article is read or not without scrolling back to the top. In a long article, this can mean a LOT of scrolling. Is there a chance that something could change between read/unread states? (It doesn't have to be a checkbox, although that was fairly intuitive. For example, it could go between "Mark Unread" and "Mark Read".)

**Comment by disconn3ct** [comment]
Works great. Thanks!!

**Comment by maliayas** [comment]
Good approach.
