### ISSUE TITLE
Mark As Read at bottom not always showing up.

### ISSUE THREAD

**Issue by zedmike** [g2ttrss/g2ttrss-mobile#36]
When in a feed are less articles than the value of pref_Feed_limit from the js/g2tt-config.js the "Mark these items as read" link at the bottom of the feed doesn't show up anymore.

**Comment by zedmike** [comment]
The link is actually still there but hidden with  style="display: none;" 

<div class="load-more-message" style="display: none;">Mark these items as read</div>

It should be 

<div class="load-more-message">Mark these items as read</div>

**Comment by mrjeremy28** [comment]
Thanks zedmike. I just got back into working on this. I'll look into it as well as the others.

**Comment by g2ttrss** [comment]
This brings to attention that when the switch to the "big text" being mark as read and the "little link" being read more broke things. Looks like the commit swapped the text and a few of the actions, but not all the logic. Will have to track down the commit as it was a pull request I merged without enough review apparently.

**Comment by mrjeremy28** [comment]
Sorry to hear. I haven't had chance to look at. I've actually been trying to recreate a feed reader using NodeJS and AngularJS.

**Comment by andy-isec** [comment]
Cool, sounds pretty sweet!

Yeah, pull request #34 was a whole lot of things and I was in the "I haven't touched this in forever" mode and so just kind of accepted it. Bound to have some negative side effects ;-)
