### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by pizzaazzip** [g2ttrss/g2ttrss-mobile#37]
My TT-RSS (v15.7) installation is located at http://read.nameofdomain.com so I cloned the github installation to http://mread.nameofdomain.com.  I am able to get a sign in page but when I punch in my credentials (the username I am using is the default <i>admin</i>), the sign in button or enter doesn't do anything.

The First few lines of my code is:
>// Config
global_ttrssUrl = "http://read.nameofdomain.com";

>// Preferences

Am I doing something incorrectly?  Are there other details I could provide?

**Comment by mrjeremy28** [comment]
did you enable API access in your TT-RSS?

**Comment by pizzaazzip** [comment]
![screen shot 2015-10-29 at 12 15 57](https://cloud.githubusercontent.com/assets/3604065/10827885/d7743f10-7e36-11e5-9b08-0052ffc06d3a.png)

Is this the one you are referring to or is there a different one?

**Comment by mrjeremy28** [comment]
Yes. That is. 

Thank you,
Jeremy

**Comment by pizzaazzip** [comment]
Huh, I wonder what could be the issue.  I host this using hostgator, I wonder if it is an issue unique to them.

**Comment by mrjeremy28** [comment]
can you look at console to see if there are any errors?

**Comment by mrjeremy28** [comment]
when i go to those URLs, they don't seem to return anything or else I could look at errors

**Comment by pizzaazzip** [comment]
I have a few 304, 500 and 200 errors, probably as a result of me messing with the file trying to get it to work.  I'll see if I can get you some more definitive answers shortly.

**Comment by pizzaazzip** [comment]
For kicks and giggles, I switched the path to be http://read.nameofdomain.com/mobile and it worked.  I'll keep the config on the other location and just drag that over every time I update.  

P.S. nameofdomain.com is not where I actually have the site hosted.  I just didn't feel like putting the real link

**Comment by pizzaazzip** [comment]
By the way, thanks for your help.

**Comment by mrjeremy28** [comment]
Good to hear. Ya I realized the domain name wasn't real after I commented.
Glad it's working
